### ISSUE TITLE
Multi line prepared statement

### ISSUE THREAD

**Issue by mikef-traction** [danneu/pg-extra#1]
Appreciate your work on this repo.
Working on my first koa/vuejs/node/postgres project so apologies if this is a silly question. I have large bulk inserts to perform. ie:
INSERT INTO 
  foo (col1,col2,col3)
VALUES
  (1,2,3),
  (4,5,6),
  (7,8,9),
......
I'm not sure how to build out very long sql statements. I've attempted something like https://github.com/brianc/node-postgres/issues/530#issuecomment-269112222 but I get an error that client.query expects either sql or __raw within client.query. 

Could you suggest a way to build out the query?  Could be many many lines long. Cheers.

**Comment by danneu** [comment]
I personally use a query builder like [knex][1] for more dynamic queries, like an `INSERT` with an arbitrary amount of `VALUES` or a `/search` endpoint that may have any number of filters.

```javascript
const knex = require('knex')
const {_unsafe} = require('pg-extra')

exports.insertUsers = function (users) {
    const sql = knex('users').insert(users.map((u) => ({ uname: u.uname }))).toString()
    return client._query(sql)
}
```

Notice that `client._query()` bypasses the `sql/_unsafe` requirement.

I should update the README to provide examples like this.

[1]: http://knexjs.org/

**Comment by mikef-traction** [comment]
That is awesome. Thanks!

**Comment by danneu** [comment]
Updated the readme with this example.

This is the same thing you'd do whether you use pg-extra or the underlying `pg` module directly since you can't create a dynamic query with `INSERT INTO ... VALUES ($1, $2), ($3, $4), ...` syntax.
