### ISSUE TITLE
Ignore nil values when applying binding-flattening optimization.

### ISSUE THREAD

**Issue by danneu** [danneu/pg-extra#11]
In #4 I introduce an optimization that reuses bindings to reduce bytes over the wire.

However, consider this:

```javascript
{
    text: "insert into foo (date, string) values ($1, $1)",
    values: [null]
}
```

My optimization flattens null, but Postgres complains that the same binding is trying to be a timestamp and also a text datatype and will reject the query.

One solution is to cast $1::timestamptz, $1::text appropriately, but that would be very annoying.

Instead, I think a simple solution would be to simply ignore applying the optimization to falsey values. After all, the point of the optimization is to avoid over-sending large data, not a couple extra nulls.

**Comment by lattam** [comment]
Hello, this fix does not seem to be part of the latest version 2.0.2. Would it be possible to create a new version and publish it on npm? Thank you.

**Comment by danneu** [comment]
Sorry, this got lost in my notifications.

I think I'm going to drop the deduping optimization or make it opt-in due to issues reusing $1, $2, etc. bindings for columns of different datatypes.
