### ISSUE TITLE
Breaks on latest node-pg 7

### ISSUE THREAD

**Issue by uniibu** [danneu/pg-extra#5]
Hi, is this repo still maintained? Anyway, ive been using this for some months now, and coz of the latest node-pg vulnerability, i had to update to the latest, and due to that, this now breaks.

 The problem is that pg extended it own pg.Pool using `util.inherits` there for simply monkey-patching/extending it via prototype won't work.  

So since it uses util.inherits, in which pg.Pool is the 'superContructor' we can then extend it using  `constructor.super_`. So now we can extend it using `pg.Pool.super_.prototype` 

Cheers!

**Comment by danneu** [comment]
Thanks, I'll take a look.

It's maintained in the sense that we are probably the only two users and I didn't know node-postgres was updated. 😄

**Comment by danneu** [comment]
@uniibu seems that I can avoid this situation going forward by setting `pg` as a peer dependency.

looks like i should first publish a stable release that specifies the versions of `pg` that pg-extra currently supports.

and then i'll publish a `1.0.0` that works with the latest pg stable with a peer dependency that specifies that.

**Comment by uniibu** [comment]
yeah i think thats best move to move with this, since changing it would be breaking for others.

**Comment by danneu** [comment]
@uniibu Thanks for looking into it and providing the `.super_` hint. 

I published two releases:

- A final `v0.0.x` release with `peerDependencies: { pg: "<7.0" }`
- A `v0.1.0` release with `peerDependencies: { pg: ">=7.3" }`.
